// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	Description string
	Done        bool
	CreatedAt   sql.NullTime
}
